apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-values
  namespace: flux-system
data:
  values.yaml: |
    persistence:
      enabled: true
      size: 1Gi
    ingress:
      enabled: true
      hosts:
        - grafana.lab
      tls:
        - secretName: lab-tls
          hosts:
            - grafana.lab
