apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m
  values:
    alertmanager:
      enabled: false
    server:
      persistentVolume:
        enabled: true
        size: 1Gi
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - prometheus.lab
        tls:
          - secretName: lab-tls
            hosts:
              - prometheus.lab
